# Generated by Django 5.0.3 on 2024-03-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_description_goal_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='content',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
