# Generated by Django 5.0.3 on 2024-03-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTarget',
            fields=[
                ('target_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=255)),
            ],
        ),
    ]
