# Generated by Django 5.0.3 on 2024-03-22 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_goal_content_alter_goal_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='myapp.goal')),
            ],
        ),
    ]
