# Generated by Django 5.0.3 on 2024-03-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_testtarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTodo',
            fields=[
                ('todo_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('target_id', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
            ],
        ),
    ]
