# Generated by Django 5.0.3 on 2024-03-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_testtarget_target_id_alter_testtodo_todo_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User0322',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
